//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagementWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ApartmentID { get; set; }
        public int NumberOfRooms { get; set; }
        public decimal Rent { get; set; }
        public string Status { get; set; }
        public int PropertyID { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
