//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Managment_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ApartmentID { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<decimal> Rent { get; set; }
        public string Status { get; set; }
        public Nullable<int> PropertyID { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
