//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PropertyRentalManagementWebSiteEntities2 : DbContext
    {
        public PropertyRentalManagementWebSiteEntities2()
            : base("name=PropertyRentalManagementWebSiteEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
